CREATE TABLE IF NOT EXISTS imdb (
    tconst VARCHAR(12) PRIMARY KEY NOT NULL,
    year SMALLINT NOT NULL DEFAULT 0,
    genres TEXT NOT NULL DEFAULT '',
    nconsts TEXT NOT NULL DEFAULT '',
    rating REAL NOT NULL DEFAULT 0.0,
    votes INTEGER NOT NULL DEFAULT 0
);
