// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.3
// source: recommender.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Filter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to MinVotesOneof:
	//
	//	*Filter_MinVotes
	MinVotesOneof isFilter_MinVotesOneof `protobuf_oneof:"min_votes_oneof"`
	// Types that are assignable to MaxVotesOneof:
	//
	//	*Filter_MaxVotes
	MaxVotesOneof isFilter_MaxVotesOneof `protobuf_oneof:"max_votes_oneof"`
	// Types that are assignable to MinYearOneof:
	//
	//	*Filter_MinYear
	MinYearOneof isFilter_MinYearOneof `protobuf_oneof:"min_year_oneof"`
	// Types that are assignable to MaxYearOneof:
	//
	//	*Filter_MaxYear
	MaxYearOneof isFilter_MaxYearOneof `protobuf_oneof:"max_year_oneof"`
	// Types that are assignable to MinRatingOneof:
	//
	//	*Filter_MinRating
	MinRatingOneof isFilter_MinRatingOneof `protobuf_oneof:"min_rating_oneof"`
	// Types that are assignable to MaxRatingOneof:
	//
	//	*Filter_MaxRating
	MaxRatingOneof isFilter_MaxRatingOneof `protobuf_oneof:"max_rating_oneof"`
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_recommender_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_recommender_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_recommender_proto_rawDescGZIP(), []int{0}
}

func (m *Filter) GetMinVotesOneof() isFilter_MinVotesOneof {
	if m != nil {
		return m.MinVotesOneof
	}
	return nil
}

func (x *Filter) GetMinVotes() uint32 {
	if x, ok := x.GetMinVotesOneof().(*Filter_MinVotes); ok {
		return x.MinVotes
	}
	return 0
}

func (m *Filter) GetMaxVotesOneof() isFilter_MaxVotesOneof {
	if m != nil {
		return m.MaxVotesOneof
	}
	return nil
}

func (x *Filter) GetMaxVotes() uint32 {
	if x, ok := x.GetMaxVotesOneof().(*Filter_MaxVotes); ok {
		return x.MaxVotes
	}
	return 0
}

func (m *Filter) GetMinYearOneof() isFilter_MinYearOneof {
	if m != nil {
		return m.MinYearOneof
	}
	return nil
}

func (x *Filter) GetMinYear() uint32 {
	if x, ok := x.GetMinYearOneof().(*Filter_MinYear); ok {
		return x.MinYear
	}
	return 0
}

func (m *Filter) GetMaxYearOneof() isFilter_MaxYearOneof {
	if m != nil {
		return m.MaxYearOneof
	}
	return nil
}

func (x *Filter) GetMaxYear() uint32 {
	if x, ok := x.GetMaxYearOneof().(*Filter_MaxYear); ok {
		return x.MaxYear
	}
	return 0
}

func (m *Filter) GetMinRatingOneof() isFilter_MinRatingOneof {
	if m != nil {
		return m.MinRatingOneof
	}
	return nil
}

func (x *Filter) GetMinRating() float32 {
	if x, ok := x.GetMinRatingOneof().(*Filter_MinRating); ok {
		return x.MinRating
	}
	return 0
}

func (m *Filter) GetMaxRatingOneof() isFilter_MaxRatingOneof {
	if m != nil {
		return m.MaxRatingOneof
	}
	return nil
}

func (x *Filter) GetMaxRating() float32 {
	if x, ok := x.GetMaxRatingOneof().(*Filter_MaxRating); ok {
		return x.MaxRating
	}
	return 0
}

type isFilter_MinVotesOneof interface {
	isFilter_MinVotesOneof()
}

type Filter_MinVotes struct {
	MinVotes uint32 `protobuf:"varint,1,opt,name=min_votes,json=minVotes,proto3,oneof"`
}

func (*Filter_MinVotes) isFilter_MinVotesOneof() {}

type isFilter_MaxVotesOneof interface {
	isFilter_MaxVotesOneof()
}

type Filter_MaxVotes struct {
	MaxVotes uint32 `protobuf:"varint,2,opt,name=max_votes,json=maxVotes,proto3,oneof"`
}

func (*Filter_MaxVotes) isFilter_MaxVotesOneof() {}

type isFilter_MinYearOneof interface {
	isFilter_MinYearOneof()
}

type Filter_MinYear struct {
	MinYear uint32 `protobuf:"varint,3,opt,name=min_year,json=minYear,proto3,oneof"`
}

func (*Filter_MinYear) isFilter_MinYearOneof() {}

type isFilter_MaxYearOneof interface {
	isFilter_MaxYearOneof()
}

type Filter_MaxYear struct {
	MaxYear uint32 `protobuf:"varint,4,opt,name=max_year,json=maxYear,proto3,oneof"`
}

func (*Filter_MaxYear) isFilter_MaxYearOneof() {}

type isFilter_MinRatingOneof interface {
	isFilter_MinRatingOneof()
}

type Filter_MinRating struct {
	MinRating float32 `protobuf:"fixed32,5,opt,name=min_rating,json=minRating,proto3,oneof"`
}

func (*Filter_MinRating) isFilter_MinRatingOneof() {}

type isFilter_MaxRatingOneof interface {
	isFilter_MaxRatingOneof()
}

type Filter_MaxRating struct {
	MaxRating float32 `protobuf:"fixed32,6,opt,name=max_rating,json=maxRating,proto3,oneof"`
}

func (*Filter_MaxRating) isFilter_MaxRatingOneof() {}

type Weight struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Year    uint32 `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Rating  uint32 `protobuf:"varint,2,opt,name=rating,proto3" json:"rating,omitempty"`
	Genres  uint32 `protobuf:"varint,3,opt,name=genres,proto3" json:"genres,omitempty"`
	Nconsts uint32 `protobuf:"varint,4,opt,name=nconsts,proto3" json:"nconsts,omitempty"`
}

func (x *Weight) Reset() {
	*x = Weight{}
	mi := &file_recommender_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Weight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Weight) ProtoMessage() {}

func (x *Weight) ProtoReflect() protoreflect.Message {
	mi := &file_recommender_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Weight.ProtoReflect.Descriptor instead.
func (*Weight) Descriptor() ([]byte, []int) {
	return file_recommender_proto_rawDescGZIP(), []int{1}
}

func (x *Weight) GetYear() uint32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *Weight) GetRating() uint32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Weight) GetGenres() uint32 {
	if x != nil {
		return x.Genres
	}
	return 0
}

func (x *Weight) GetNconsts() uint32 {
	if x != nil {
		return x.Nconsts
	}
	return 0
}

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tconsts []string `protobuf:"bytes,1,rep,name=tconsts,proto3" json:"tconsts,omitempty"`
	N       uint32   `protobuf:"varint,2,opt,name=n,proto3" json:"n,omitempty"`
	Filter  *Filter  `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	Weight  *Weight  `protobuf:"bytes,4,opt,name=weight,proto3" json:"weight,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_recommender_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_recommender_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_recommender_proto_rawDescGZIP(), []int{2}
}

func (x *Request) GetTconsts() []string {
	if x != nil {
		return x.Tconsts
	}
	return nil
}

func (x *Request) GetN() uint32 {
	if x != nil {
		return x.N
	}
	return 0
}

func (x *Request) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *Request) GetWeight() *Weight {
	if x != nil {
		return x.Weight
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Movies []*RecommendedMovie `protobuf:"bytes,1,rep,name=movies,proto3" json:"movies,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_recommender_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_recommender_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_recommender_proto_rawDescGZIP(), []int{3}
}

func (x *Response) GetMovies() []*RecommendedMovie {
	if x != nil {
		return x.Movies
	}
	return nil
}

type RecommendedMovie struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tconst  string   `protobuf:"bytes,1,opt,name=tconst,proto3" json:"tconst,omitempty"`
	Weights []string `protobuf:"bytes,2,rep,name=weights,proto3" json:"weights,omitempty"`
}

func (x *RecommendedMovie) Reset() {
	*x = RecommendedMovie{}
	mi := &file_recommender_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendedMovie) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendedMovie) ProtoMessage() {}

func (x *RecommendedMovie) ProtoReflect() protoreflect.Message {
	mi := &file_recommender_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendedMovie.ProtoReflect.Descriptor instead.
func (*RecommendedMovie) Descriptor() ([]byte, []int) {
	return file_recommender_proto_rawDescGZIP(), []int{4}
}

func (x *RecommendedMovie) GetTconst() string {
	if x != nil {
		return x.Tconst
	}
	return ""
}

func (x *RecommendedMovie) GetWeights() []string {
	if x != nil {
		return x.Weights
	}
	return nil
}

var File_recommender_proto protoreflect.FileDescriptor

var file_recommender_proto_rawDesc = []byte{
	0x0a, 0x11, 0x72, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x72, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x22, 0xb4, 0x02, 0x0a, 0x06, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x09, 0x6d,
	0x69, 0x6e, 0x5f, 0x76, 0x6f, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00,
	0x52, 0x08, 0x6d, 0x69, 0x6e, 0x56, 0x6f, 0x74, 0x65, 0x73, 0x12, 0x1d, 0x0a, 0x09, 0x6d, 0x61,
	0x78, 0x5f, 0x76, 0x6f, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x01, 0x52,
	0x08, 0x6d, 0x61, 0x78, 0x56, 0x6f, 0x74, 0x65, 0x73, 0x12, 0x1b, 0x0a, 0x08, 0x6d, 0x69, 0x6e,
	0x5f, 0x79, 0x65, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x02, 0x52, 0x07, 0x6d,
	0x69, 0x6e, 0x59, 0x65, 0x61, 0x72, 0x12, 0x1b, 0x0a, 0x08, 0x6d, 0x61, 0x78, 0x5f, 0x79, 0x65,
	0x61, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x03, 0x52, 0x07, 0x6d, 0x61, 0x78, 0x59,
	0x65, 0x61, 0x72, 0x12, 0x1f, 0x0a, 0x0a, 0x6d, 0x69, 0x6e, 0x5f, 0x72, 0x61, 0x74, 0x69, 0x6e,
	0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x48, 0x04, 0x52, 0x09, 0x6d, 0x69, 0x6e, 0x52, 0x61,
	0x74, 0x69, 0x6e, 0x67, 0x12, 0x1f, 0x0a, 0x0a, 0x6d, 0x61, 0x78, 0x5f, 0x72, 0x61, 0x74, 0x69,
	0x6e, 0x67, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x48, 0x05, 0x52, 0x09, 0x6d, 0x61, 0x78, 0x52,
	0x61, 0x74, 0x69, 0x6e, 0x67, 0x42, 0x11, 0x0a, 0x0f, 0x6d, 0x69, 0x6e, 0x5f, 0x76, 0x6f, 0x74,
	0x65, 0x73, 0x5f, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x42, 0x11, 0x0a, 0x0f, 0x6d, 0x61, 0x78, 0x5f,
	0x76, 0x6f, 0x74, 0x65, 0x73, 0x5f, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x42, 0x10, 0x0a, 0x0e, 0x6d,
	0x69, 0x6e, 0x5f, 0x79, 0x65, 0x61, 0x72, 0x5f, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x42, 0x10, 0x0a,
	0x0e, 0x6d, 0x61, 0x78, 0x5f, 0x79, 0x65, 0x61, 0x72, 0x5f, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x42,
	0x12, 0x0a, 0x10, 0x6d, 0x69, 0x6e, 0x5f, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x6f, 0x6e,
	0x65, 0x6f, 0x66, 0x42, 0x12, 0x0a, 0x10, 0x6d, 0x61, 0x78, 0x5f, 0x72, 0x61, 0x74, 0x69, 0x6e,
	0x67, 0x5f, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x22, 0x66, 0x0a, 0x06, 0x57, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x79, 0x65, 0x61, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x04, 0x79, 0x65, 0x61, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x16, 0x0a,
	0x06, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x67,
	0x65, 0x6e, 0x72, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x73,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x6e, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x73, 0x22,
	0x8b, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x74,
	0x63, 0x6f, 0x6e, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x74, 0x63,
	0x6f, 0x6e, 0x73, 0x74, 0x73, 0x12, 0x0c, 0x0a, 0x01, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x01, 0x6e, 0x12, 0x2b, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x12, 0x2b, 0x0a, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x57,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x52, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0x41, 0x0a,
	0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x06, 0x6d, 0x6f, 0x76,
	0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x72, 0x65, 0x63, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x64, 0x65, 0x64, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x06, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x73,
	0x22, 0x44, 0x0a, 0x10, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x4d,
	0x6f, 0x76, 0x69, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x77,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x73, 0x32, 0x52, 0x0a, 0x0b, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x43, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x14, 0x2e, 0x72, 0x65,
	0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x15, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x79, 0x6b, 0x68, 0x61, 0x6e, 0x73,
	0x2f, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x72, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70,
	0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_recommender_proto_rawDescOnce sync.Once
	file_recommender_proto_rawDescData = file_recommender_proto_rawDesc
)

func file_recommender_proto_rawDescGZIP() []byte {
	file_recommender_proto_rawDescOnce.Do(func() {
		file_recommender_proto_rawDescData = protoimpl.X.CompressGZIP(file_recommender_proto_rawDescData)
	})
	return file_recommender_proto_rawDescData
}

var file_recommender_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_recommender_proto_goTypes = []any{
	(*Filter)(nil),           // 0: recommender.Filter
	(*Weight)(nil),           // 1: recommender.Weight
	(*Request)(nil),          // 2: recommender.Request
	(*Response)(nil),         // 3: recommender.Response
	(*RecommendedMovie)(nil), // 4: recommender.RecommendedMovie
}
var file_recommender_proto_depIdxs = []int32{
	0, // 0: recommender.Request.filter:type_name -> recommender.Filter
	1, // 1: recommender.Request.weight:type_name -> recommender.Weight
	4, // 2: recommender.Response.movies:type_name -> recommender.RecommendedMovie
	2, // 3: recommender.Recommender.GetRecommendations:input_type -> recommender.Request
	3, // 4: recommender.Recommender.GetRecommendations:output_type -> recommender.Response
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_recommender_proto_init() }
func file_recommender_proto_init() {
	if File_recommender_proto != nil {
		return
	}
	file_recommender_proto_msgTypes[0].OneofWrappers = []any{
		(*Filter_MinVotes)(nil),
		(*Filter_MaxVotes)(nil),
		(*Filter_MinYear)(nil),
		(*Filter_MaxYear)(nil),
		(*Filter_MinRating)(nil),
		(*Filter_MaxRating)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_recommender_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_recommender_proto_goTypes,
		DependencyIndexes: file_recommender_proto_depIdxs,
		MessageInfos:      file_recommender_proto_msgTypes,
	}.Build()
	File_recommender_proto = out.File
	file_recommender_proto_rawDesc = nil
	file_recommender_proto_goTypes = nil
	file_recommender_proto_depIdxs = nil
}
